### ISSUE TITLE
可以直接模拟点击或者改包

### ISSUE THREAD

**Issue by zhuweiyou** [ElementMo/LORDofCOLOR_Game#1]
我进去玩了一下，这个游戏其实没这么麻烦

直接两循环，隔几个像素 tap 一次就好

根本不用图像操作，因为它允许点错

**Comment by zhuweiyou** [comment]
抓包直接改成顶级了

![image](https://user-images.githubusercontent.com/8413791/36061343-e337438e-0e93-11e8-87d9-839f7915b416.png)

![image](https://user-images.githubusercontent.com/8413791/36061346-ea6af218-0e93-11e8-8fdf-234377ce2a0a.png)

![image](https://user-images.githubusercontent.com/8413791/36061347-f138525c-0e93-11e8-8129-d2a71bf9c308.png)

第三个最强王者是我

**Comment by ElementMo** [comment]
这个不允许点错吧....好像点错一次扣两秒...

直接改包哈哈哈哈哈
厉害厉害~强强强！！

**Comment by zhuweiyou** [comment]
连个签名都没有做啊。

宣传一下我的辅助 https://github.com/game-helper 哈哈

**Comment by ElementMo** [comment]
老哥很稳

**Comment by zhuweiyou** [comment]
还是你稳

**Comment by zhuweiyou** [comment]
还是你稳
